### PR TITLE
Make Meilisearch calls async

### PR DESCRIPTION
**Pull request by sanders41**
This PR changes from the `meilisearch` python package to `meilisearch-python-async`. This allows the calls to Meilisearch to also be async. The `meilisearch-python-async` package has built in async wait functionality so I used that in place of the custom `task_completion`. I wasn't sure on indexing times here so I set the time out at 300000 ms (5 minutes), this may need to be adjusted.

I also used the `add_documents_in_batches` functionality from `meilisearch-python-async`. This will use [gather](https://docs.python.org/3/library/asyncio-task.html#running-tasks-concurrently) from `asyncio` to send the documents concurrently.

I didn't see any tests present so I don't think there is a test suite to run? If you like the idea of this update, but have issues let me know and I can make changes.

### CODE REVIEW

**Comment by scmmmh** [comment]
Thank you for that. That's really neat, although I am slightly annoyed that I didn't find your library in the first place :-).

I currently haven't got time to review this properly, but this looks to definitely reduce my maintenance burden, so will go in at some point. Just one quick question. Is there a reason why in the task timeout it is not possible to specify that I'm happy to wait forever?

**Comment by sanders41** [comment]
> Just one quick question. Is there a reason why in the task timeout it is not possible to specify that I'm happy to wait forever?

I figured people would want a timeout so they didn't have to wait forever. There is no real reason I couldn't allow passing `None` for the timeout and let it go forever though. I'll make that update in the library.

**Comment by sanders41** [comment]
Alright, I made a new release of `meilisearch-python-async` that allows no timeout on the wait and made the updates here. No rush on my part to get it reviewed so whenever you have time.

**Comment by scmmmh** [comment]
Nice. Thank you for your contribution!

**Pull request merged**
